apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o .k8s/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: lgca
  name: lgca
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lgca
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o .k8s/
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: lgca
    spec:
      containers:
        - image: jasperkroes/mmb:1.0.1
          name: lgca
          resources: {}
      restartPolicy: Always
status: {}
